### ISSUE TITLE
sha256sum check error because of wrong format, missing one space symbol.

### ISSUE THREAD

**Issue by rooa** [unnonouno/cudnnenv#48]
I failed to install `v6-cuda8` when I executed `cudnnenv install v6-cuda8`. The error indicated that the internal shell command returned non-zero exit status. It seems to be echo-ing checksum in the source ([`__init__.py: L49`](https://github.com/unnonouno/cudnnenv/blob/master/cudnnenv/__init__.py#L49)) needs exactly **two** spaces between words to be successfully checked. Indeed, I could install without problems after adding one more space.

[This reference](https://unix.stackexchange.com/questions/139891/why-does-verifying-sha256-checksum-with-sha256sum-fail-on-debian-and-work-on-u) says the spacing is ignored in newer versions of `sha256sum`, but I weirdly encountered this problem while having version `8.4`. I guess it's better to just add another space to make sure checksum verification won't fail.

Please see below:
```shell
$ sha256sum --version
sha256sum (GNU coreutils) 8.4
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ echo "9b09110af48c9a4d7b6344eb4b3e344daa84987ed6177d5c44319732f3bb7f9c cudnn-8.0-linux-x64-v6.0.tgz" | sha256sum -cw
sha256sum: standard input: 1: improperly formatted SHA256 checksum line
sha256sum: standard input: no properly formatted SHA256 checksum lines found

$ echo "9b09110af48c9a4d7b6344eb4b3e344daa84987ed6177d5c44319732f3bb7f9c  cudnn-8.0-linux-x64-v6.0.tgz" | sha256sum -cw
cudnn-8.0-linux-x64-v6.0.tgz: OK
```

**Comment by unnonouno** [comment]
Thank you for writing a problem and sorry for late reply. Ok, i'll fix it.
